server:
  port: 8050

spring:
  application:
    name: gateway-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
    gateway:
      discovery:
        locator:
          enabled: true 
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
